services:
  laravel-docker:
    container_name: laravel-docker
    build: ./back
    ports:
      - 8000:80

  vue-docker:
    container_name: react-docker
    build: ./front
    ports:
      - 80:80

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    ports:
      - 3306:3306