services:
  laravel-app:
    container_name: temposwim-laravel
    build: ./back
    ports:
      - 8000:80
    depends_on:
      - mysql_db

  react-app:
    container_name: temposwim-react
    build: ./front
    ports:
      - 3000:80
    depends_on:
      - laravel-app

  mysql_db:
    image: mysql:8.0
    container_name: temposwim-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: temposwim
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: