name: CI/CD Pipeline TempoSwim

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  #test:
    #runs-on: ubuntu-latest
    #steps:
      #- name: Checkout code
      #  uses: actions/checkout@v4

      #- name: Set up Node.js
      #  uses: actions/setup-node@v4
       # with:
       #   node-version: '20'

     # - name: Install Frontend Dependencies
      #  run: |
       #   cd front
        #  npm ci

      - #name: Run Frontend Tests
        #run: |
        #  cd front
         # npm test -- --watchAll=false

      - #name: Set up PHP
        #uses: shivammathur/setup-php@v2
        #with:
        #  php-version: '8.2'
        #  extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, json, pdo
         # coverage: none

      - #name: Install Backend Dependencies
        #run: |
        #  cd back
        #  composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - #name: Run Backend Tests
        #run: |
        #  cd back
         # cp .env.example .env
        # php artisan key:generate
        #  php artisan test

  build-and-push:
    # needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Laravel backend
        uses: docker/build-push-action@v5
        with:
          context: ./back
          push: true
          tags: ghcr.io/nataswim/temposwim-api-prod:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push React frontend
        uses: docker/build-push-action@v5
        with:
          context: ./front
          push: true
          tags: ghcr.io/nataswim/temposwim-spa-prod:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            cd /opt/temposwim
            ./deploy.sh