name: temposwim-app

on:
  push:
    branches:
      - "main"
jobs:
  tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install Docker
      uses: hoverkraft-tech/compose-action@v2.0.1
    
    - name: Start containers
      run: docker-compose up -d
    
    - name: Wait for containers to be ready
      run: sleep 10s
      shell: bash
    
    - name: Run migrations
      run: docker exec temposwim-laravel bash -c "php artisan migrate"
    
    - name: Seed database
      run: docker exec temposwim-laravel bash -c "php artisan db:seed"
    
    - name: Run Laravel tests
      run: docker exec temposwim-laravel bash -c "php artisan test"
    
    - name: Run React tests
      run: docker exec temposwim-react bash -c "npm test"

  build-and-push-image-api-prod:
    needs:
      - tests
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Laravel Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./back
          build-args: |
            "MODE=prod"
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/temposwim-api-prod:latest
            ghcr.io/${{ github.repository_owner }}/temposwim-api-prod:${{ github.sha }}

  build-and-push-image-spa-prod:
    needs:
      - tests
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push React Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./front
          build-args: |
            "MODE=prod"
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/temposwim-spa-prod:latest
            ghcr.io/${{ github.repository_owner }}/temposwim-spa-prod:${{ github.sha }}

  deploy:
    needs:
      - build-and-push-image-api-prod
      - build-and-push-image-spa-prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /opt/temposwim
            docker-compose pull
            docker-compose down
            docker-compose up -d
            docker exec temposwim-laravel bash -c "php artisan migrate --force"