name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Permet aussi de déclencher manuellement le workflow
  workflow_dispatch:

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Laravel image
        uses: docker/build-push-action@v5
        with:
          context: ./back
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/temposwim-api-prod:latest
            ghcr.io/${{ github.repository_owner }}/temposwim-api-prod:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-and-push-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push React image
        uses: docker/build-push-action@v5
        with:
          context: ./front
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/temposwim-spa-prod:latest
            ghcr.io/${{ github.repository_owner }}/temposwim-spa-prod:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max